# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'evacacela/pokemon-challenge'

steps:
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'
- task: aws-eks-authenticator@0
  inputs:
    clusterName: 'mundose-eks-pin'
    awsCredentials: 'eks-service-connection'
    regionName: 'us-east-1'
- task: CmdLine@2
  displayName: kubeconfig was configured
  inputs:
    script: |
      aws eks --region us-east-1 update-kubeconfig --name mundose-eks-pin
    failOnStderr: true
- task: CmdLine@2
  displayName: Destroy the app from k8s cluster
  inputs:
    script: |
      kubectl delete -f deployment/
    failOnStderr: true