# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'lcardozo05/pokemon-challenge'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    containerRegistry: 'docker-registry'
    repository: $(imageName)
    command: 'buildAndPush'
    tags: |
        0.1.0
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'
- task: aws-eks-authenticator@0
  inputs:
    clusterName: 'mundose-eks-pin'
    awsCredentials: 'eks-service-connection'
    regionName: 'us-east-1'
- task: CmdLine@2
  displayName: kubeconfig was configured
  inputs:
    script: |
      aws eks --region us-east-1 update-kubeconfig --name mundose-eks-pin
    failOnStderr: true
- task: CmdLine@2
  displayName: Deploy the app on k8s cluster
  inputs:
    script: |
      kubectl apply -f deployment/
    failOnStderr: true