---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pokemon-challenge-deployment
  labels:
    app: pokemon-challenge
spec:
  selector:
    matchLabels:
      app: pokemon-challenge  
  replicas: 3 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: pokemon-challenge
    spec:
      containers:
      - name: pokemon-challenge
        image: evacacela/pokemon-challenge:0.1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-challenge
  namespace: default
  labels:
    app: pokemon-challenge
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pokemon-challenge
  type: LoadBalancer